ContainerAppConsoleLogs_CL
| where TimeGenerated > ago(1m)
| extend PacificTime = datetime_utc_to_local(TimeGenerated, 'US/Pacific')
| project PacificTime, ContainerGroupName_s, Log_s
| order by PacificTime asc

ContainerAppConsoleLogs_CL
| where TimeGenerated > ago(10m)
| where Log_s contains "HEAD /health"
| summarize LogsPerMinute = count() by ContainerGroupName_s, bin(TimeGenerated, 1m)
| order by TimeGenerated asc, ContainerGroupName_s asc

AppRequests
| where TimeGenerated > ago(1h)
| where Url !contains "/health"
| summarize count() by OperationName
| order by count_ desc

AppDependencies
| where TimeGenerated > ago(1h)
| summarize count() by AppRoleName, Name, Target, Type
| order by count_ desc

Usage
| where TimeGenerated > ago(12h)
| summarize TotalGB = sum(Quantity) / 1000 by DataType
| order by TotalGB desc


