# modules/storage/main.tf
# ─────────────────────────────────────────────────────────────────────────────
# Azure Storage Account
#
# Creates:
#   - Storage Account (Standard_LRS, StorageV2 — matches awardnominationmodels)
#   - Blob containers: ml-models, award-nomination-extracts, certificate-templates, certificates, tfstate
#   - Private endpoint → subnet-privatelinks
#   - Private DNS zone group registration
#   - Network rules — deny public, whitelist local IPs + ACA subnets
# ─────────────────────────────────────────────────────────────────────────────

resource "azurerm_storage_account" "storage" {
  name                     = var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  min_tls_version          = "TLS1_2"

  # Disable public blob access — SAS tokens still work
  allow_nested_items_to_be_public = false

  # ── Artifact recovery ───────────────────────────────────────────────────────
  # Both ML pipelines overwrite their model artifacts in place:
  #   modeling.train_rf_model._upload_artefact() -> upload_blob(..., overwrite=True)
  #     random_forest_tenant_<N>.pkl            (Random Forest)
  #     gnn_encoder_tenant_<N>.pt              (GNN encoder — audit/retrain)
  #     gnn_head_tenant_<N>.pt                 (GNN decoder — read by inference)
  #
  # Without versioning that overwrite is destructive: a bad weekly run replaces
  # the last known-good model and there is no way back except retraining, which
  # reproduces the same bad model from the same bad inputs. integrity-check
  # picks the replacement up within one cache eviction.
  #
  # Versioning makes every overwrite recoverable — promote a prior version back
  # to current with a single `az storage blob copy`. Soft delete covers the
  # other failure mode, an accidental delete rather than an overwrite.
  #
  # Transparent to application code: readers still get the current version, and
  # upload_blob(overwrite=True) is unchanged. No code change accompanies this.
  blob_properties {
    versioning_enabled = var.blob_versioning_enabled

    # Recover a deleted blob (as opposed to an overwritten one).
    delete_retention_policy {
      days = var.blob_soft_delete_retention_days
    }

    # Recover an accidentally deleted container. Cheap insurance: a deleted
    # container takes every model for every tenant with it.
    container_delete_retention_policy {
      days = var.container_soft_delete_retention_days
    }
  }

  tags = var.tags
}

# ── Version lifecycle ─────────────────────────────────────────────────────────
# Versioning without expiry grows without bound. The weekly job rewrites one
# .pkl plus two .pt files per tenant per run, so ml-models accrues
# (3 x tenants) versions a week and needs a shorter, explicit retention than the
# write-once containers.
#
# Retention has to outlive the detection loop it protects: a model regression is
# usually noticed over several weekly cycles, not immediately, so the default
# keeps roughly a quarter of history.
resource "azurerm_storage_management_policy" "blob_versions" {
  count              = var.blob_versioning_enabled ? 1 : 0
  storage_account_id = azurerm_storage_account.storage.id

  # ML model artifacts — .pkl (RF) and .pt (GNN).
  rule {
    name    = "expire-old-model-versions"
    enabled = true

    filters {
      prefix_match = ["ml-models/"]
      blob_types   = ["blockBlob"]
    }

    actions {
      version {
        delete_after_days_since_creation = var.model_version_retention_days
      }
    }
  }

  # Everything else on the account: certificates, extracts, certificate
  # templates, and tfstate. These are effectively write-once, so they accrue
  # few versions, but an unbounded policy is still an unbounded cost line.
  rule {
    name    = "expire-old-non-model-versions"
    enabled = true

    filters {
      prefix_match = [
        "certificates/",
        "certificate-templates/",
        "award-nomination-extracts/",
        "tfstate/",
      ]
      blob_types = ["blockBlob"]
    }

    actions {
      version {
        delete_after_days_since_creation = var.general_version_retention_days
      }
    }
  }
}

# ── Blob containers ───────────────────────────────────────────────────────────

# ML models — fraud_detection_model.pkl etc.
resource "azurerm_storage_container" "ml_models" {
  name                  = "ml-models"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

# PDF/Excel/CSV exports generated by the AI agent
resource "azurerm_storage_container" "extracts" {
  name                  = "award-nomination-extracts"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

# Award certificate templates — base design(s) overlaid at generation time.
# Seeded with default_certificate.png; tenants may add their own templates.
resource "azurerm_storage_container" "certificate_templates" {
  name                  = "certificate-templates"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

# Generated award certificate PDFs (one per approved nomination, cached).
resource "azurerm_storage_container" "certificates" {
  name                  = "certificates"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

# Terraform state — same storage account, separate container
resource "azurerm_storage_container" "tfstate" {
  name                  = "tfstate"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}

# ── Network rules ─────────────────────────────────────────────────────────────
resource "azurerm_storage_account_network_rules" "rules" {
  storage_account_id = azurerm_storage_account.storage.id

  default_action = "Deny"
  bypass         = ["AzureServices"]

  # Local IP whitelist for debugging
  ip_rules = var.allowed_ips

  # ACA subnets get direct access via service endpoint
  virtual_network_subnet_ids = var.aca_subnet_ids
}

# ── Private endpoint ──────────────────────────────────────────────────────────
resource "azurerm_private_endpoint" "storage" {
  name                = "pe-${var.storage_account_name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.private_endpoint_subnet_id
  tags                = var.tags

  private_service_connection {
    name                           = "psc-${var.storage_account_name}"
    private_connection_resource_id = azurerm_storage_account.storage.id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "dns-group-blob"
    private_dns_zone_ids = [var.private_dns_zone_id]
  }
}
