# modules/storage/main.tf
# ─────────────────────────────────────────────────────────────────────────────
# Azure Storage Account
#
# Creates:
#   - Storage Account (Standard_LRS, StorageV2 — matches awardnominationmodels)
#   - Blob containers: ml-models, award-nomination-extracts, tfstate
#   - Private endpoint → subnet-privatelinks
#   - Private DNS zone group registration
#   - Network rules — deny public, whitelist local IPs + ACA subnets
# ─────────────────────────────────────────────────────────────────────────────

resource "azurerm_storage_account" "storage" {
  name                     = var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  min_tls_version          = "TLS1_2"

  # Disable public blob access — SAS tokens still work
  allow_nested_items_to_be_public = false

  tags = var.tags
}

# ── Blob containers ───────────────────────────────────────────────────────────

# ML models — fraud_detection_model.pkl etc.
resource "azurerm_storage_container" "ml_models" {
  name                  = "ml-models"
  storage_account_id    = azurerm_storage_account.storage.id
  container_access_type = "private"
}

# PDF/Excel/CSV exports generated by the AI agent
resource "azurerm_storage_container" "extracts" {
  name                  = "award-nomination-extracts"
  storage_account_id    = azurerm_storage_account.storage.id
  container_access_type = "private"
}

# Terraform state — same storage account, separate container
resource "azurerm_storage_container" "tfstate" {
  name                  = "tfstate"
  storage_account_id    = azurerm_storage_account.storage.id
  container_access_type = "private"
}

# ── Network rules ─────────────────────────────────────────────────────────────
resource "azurerm_storage_account_network_rules" "rules" {
  storage_account_id = azurerm_storage_account.storage.id

  default_action = "Deny"
  bypass         = ["AzureServices"]

  # Local IP whitelist for debugging
  ip_rules = var.allowed_ips

  # ACA subnets get direct access via service endpoint
  virtual_network_subnet_ids = var.aca_subnet_ids
}

# ── Private endpoint ──────────────────────────────────────────────────────────
resource "azurerm_private_endpoint" "storage" {
  name                = "pe-${var.storage_account_name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.private_endpoint_subnet_id
  tags                = var.tags

  private_service_connection {
    name                           = "psc-${var.storage_account_name}"
    private_connection_resource_id = azurerm_storage_account.storage.id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "dns-group-blob"
    private_dns_zone_ids = [var.private_dns_zone_id]
  }
}
